version: '3'

services:
  pihole:
    container_name: pihole
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1G
    dns: [10.0.0.1]
    hostname: pihole
    image: pihole/pihole:latest
    network_mode: bridge
    ports:
      - "10.0.0.2:53:53/tcp"
      - "10.0.0.2:53:53/udp"
      - "10.0.0.3:53:53/tcp"
      - "10.0.0.3:53:53/udp"
      - "7000:80/tcp"
    restart: "no"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/docker/pihole/external.conf:/etc/lighttpd/external.conf:ro
      - /etc/docker/pihole/htpasswd.users:/etc/lighttpd/htpasswd.users:ro
      - /ssd/docker/pihole/pihole:/etc/pihole
      - /var/log/docker/pihole:/var/log
